# Configuração do golangci-lint para Notification Service

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gomnd
    - lll
    - testpackage
