# Template para auth-secret.yaml
# NÃO commite este arquivo com valores reais!
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  jwt-secret: "SUBSTITUA-POR-JWT-SECRET-REAL-VIA-GITHUB-SECRETS"
