apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # URL do servidor Let's Encrypt para produção
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email para notificações (ALTERAR PARA SEU EMAIL)
    email: henrique.moraes@fiap.com.br
    
    # Secret para armazenar a chave privada da conta ACME
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # Configuração para validação HTTP-01 usando nginx
    solvers:
    - http01:
        ingress:
          class: nginx
          ingressClassName: nginx
