apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: fiapx
data:
  config.yaml: |
    server:
      port: 8080
      timeout: 60s
    cors:
      allowed_origins: "*"
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["Accept", "Authorization", "Content-Type", "X-CSRF-Token"]
      exposed_headers: ["Link"]
      allow_credentials: true
      max_age: 300
    services:
      auth:
        url: http://auth-service:8081
      upload:
        url: http://upload-service:8082
      processing:
        url: http://processing-service:8083
      storage:
        url: http://storage-service:8084
    rate_limiting:
      enabled: true
      requests_per_minute: 100
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: fiapx
type: Opaque
data:
  jwt_secret: c2VjcmV0X2NoYW5nZV9tZV9pbl9wcm9kdWN0aW9u # Base64 de "secret_change_me_in_production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: fiapx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: fiapx/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8081"
        - name: UPLOAD_SERVICE_URL
          value: "http://upload-service:8082"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8084"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: jwt_secret
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: config-volume
          mountPath: /root/config
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: fiapx
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: fiapx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: api.fiapx.local
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
