# CloudFront Distribution for FIAP-X
# Provides HTTPS termination, global CDN, and custom domain support

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudfront-config
  namespace: fiapx
data:
  # CloudFront configuration for Terraform/AWS CLI
  distribution.json: |
    {
      "DistributionConfig": {
        "CallerReference": "fiapx-distribution-2025",
        "Comment": "FIAP-X Video Processing Platform - Production Distribution",
        "DefaultCacheBehavior": {
          "TargetOriginId": "fiapx-frontend-origin",
          "ViewerProtocolPolicy": "redirect-to-https",
          "TrustedSigners": {
            "Enabled": false,
            "Quantity": 0
          },
          "ForwardedValues": {
            "QueryString": false,
            "Cookies": {
              "Forward": "none"
            }
          },
          "MinTTL": 0,
          "DefaultTTL": 86400,
          "MaxTTL": 31536000,
          "Compress": true
        },
        "CacheBehaviors": {
          "Quantity": 1,
          "Items": [
            {
              "PathPattern": "/api/*",
              "TargetOriginId": "fiapx-api-origin",
              "ViewerProtocolPolicy": "redirect-to-https",
              "TrustedSigners": {
                "Enabled": false,
                "Quantity": 0
              },
              "ForwardedValues": {
                "QueryString": true,
                "Cookies": {
                  "Forward": "all"
                },
                "Headers": {
                  "Quantity": 6,
                  "Items": [
                    "Authorization",
                    "Content-Type",
                    "Origin",
                    "Accept",
                    "User-Agent",
                    "X-Forwarded-For"
                  ]
                }
              },
              "MinTTL": 0,
              "DefaultTTL": 0,
              "MaxTTL": 31536000,
              "Compress": true
            }
          ]
        },
        "Origins": {
          "Quantity": 2,
          "Items": [
            {
              "Id": "fiapx-frontend-origin",
              "DomainName": "fiapx-frontend.s3-website-us-east-1.amazonaws.com",
              "CustomOriginConfig": {
                "HTTPPort": 80,
                "HTTPSPort": 443,
                "OriginProtocolPolicy": "http-only",
                "OriginSslProtocols": {
                  "Quantity": 1,
                  "Items": ["TLSv1.2"]
                }
              }
            },
            {
              "Id": "fiapx-api-origin", 
              "DomainName": "api-gateway-alb-123456789.us-east-1.elb.amazonaws.com",
              "CustomOriginConfig": {
                "HTTPPort": 80,
                "HTTPSPort": 443,
                "OriginProtocolPolicy": "http-only",
                "OriginSslProtocols": {
                  "Quantity": 1,
                  "Items": ["TLSv1.2"]
                }
              }
            }
          ]
        },
        "Aliases": {
          "Quantity": 1,
          "Items": ["fiapx.wecando.click"]
        },
        "ViewerCertificate": {
          "ACMCertificateArn": "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERTIFICATE_ID",
          "SSLSupportMethod": "sni-only",
          "MinimumProtocolVersion": "TLSv1.2_2021"
        },
        "Enabled": true,
        "PriceClass": "PriceClass_100",
        "HttpVersion": "http2",
        "IsIPV6Enabled": true,
        "WebACLId": "",
        "Logging": {
          "Enabled": true,
          "IncludeCookies": false,
          "Bucket": "fiapx-logs.s3.amazonaws.com",
          "Prefix": "cloudfront-logs/"
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-certificate-config
  namespace: fiapx
data:
  # SSL Certificate request configuration
  certificate-request.json: |
    {
      "DomainName": "fiapx.wecando.click",
      "SubjectAlternativeNames": [
        "*.fiapx.wecando.click"
      ],
      "ValidationMethod": "DNS",
      "DomainValidationOptions": [
        {
          "DomainName": "fiapx.wecando.click",
          "ValidationDomain": "wecando.click"
        }
      ],
      "Tags": [
        {
          "Key": "Name",
          "Value": "FIAP-X SSL Certificate"
        },
        {
          "Key": "Environment",
          "Value": "production"
        },
        {
          "Key": "Project",
          "Value": "fiapx"
        }
      ]
    }
