apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: processing-service
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: processing-service
  namespaceSelector:
    matchNames:
      - fiapx
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http
