apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: fiapx
  labels:
    app: upload-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: upload-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: fiapx
  labels:
    app: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-200-13
      containers:
      - name: upload-service
        image: hmoraes/upload-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MINIO_ENDPOINT
          value: "minio:9002"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: MINIO_USE_SSL
          value: "false"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5673/"
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "0.2"
            memory: "128Mi"
          requests:
            cpu: "0.05"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: upload-service-network-policy
  namespace: fiapx
spec:
  podSelector:
    matchLabels:
      app: upload-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: minio
    ports:
    - protocol: TCP
      port: 9002
  - to:
    - podSelector:
        matchLabels:
          app: rabbitmq
    ports:
    - protocol: TCP
      port: 5673
  - {} # Allow DNS
