#!/bin/bash

# Instruções para fazer push manual das imagens ARM64
echo "=== INSTRUÇÕES PARA PUSH MANUAL ==="
echo ""
echo "1. Conecte ao servidor:"
echo "   ssh -i ~/.ssh/keyPrincipal.pem ubuntu@worker.wecando.click"
echo ""
echo "2. Faça login no Docker Hub:"
echo "   docker login"
echo "   Username: hmoraes"
echo "   Password: [sua senha]"
echo ""
echo "3. Execute os comandos de push:"
echo "   docker push hmoraes/auth-service:arm64-latest"
echo "   docker tag hmoraes/auth-service:arm64-latest hmoraes/auth-service:latest"  
echo "   docker push hmoraes/auth-service:latest"
echo ""
echo "   docker push hmoraes/upload-service:arm64-latest"
echo "   docker tag hmoraes/upload-service:arm64-latest hmoraes/upload-service:latest"
echo "   docker push hmoraes/upload-service:latest" 
echo ""
echo "   docker push hmoraes/processing-service:arm64-latest"
echo "   docker tag hmoraes/processing-service:arm64-latest hmoraes/processing-service:latest"
echo "   docker push hmoraes/processing-service:latest"
echo ""
echo "   docker push hmoraes/storage-service:arm64-latest" 
echo "   docker tag hmoraes/storage-service:arm64-latest hmoraes/storage-service:latest"
echo "   docker push hmoraes/storage-service:latest"
echo ""
echo "4. Após o push, atualize os deployments:"
echo "   kubectl rollout restart deployment auth-service -n fiapx"
echo "   kubectl rollout restart deployment upload-service -n fiapx"
echo "   kubectl rollout restart deployment processing-service -n fiapx"
echo "   kubectl rollout restart deployment storage-service -n fiapx"
echo ""
echo "=== FIM DAS INSTRUÇÕES ==="
