apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: fiapx
type: Opaque
data:
  access-key: bWluaW9hZG1pbg== # "minioadmin" in base64
  secret-key: bWluaW9hZG1pbg== # "minioadmin" in base64
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: fiapx
  labels:
    app: minio
spec:
  ports:
  - port: 9002
    targetPort: 9000
    name: api
  - port: 9003
    targetPort: 9001
    name: console
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: fiapx
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: access-key
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: secret-key
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-storage
      resources:
        requests:
          storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: fiapx
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          sleep 30
          mc config host add myminio http://minio:9000 minioadmin minioadmin
          mc mb --ignore-existing myminio/videos
          mc admin user add myminio fiapx-upload fiapx-upload-pass
          mc admin policy set myminio readwrite user=fiapx-upload
          mc admin user add myminio fiapx-download fiapx-download-pass
          mc admin policy set myminio readonly user=fiapx-download
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
